export const ShopActionTypes = {
    FETCH_SHOP_ITEMS_START: ' FETCH_SHOP_ITEMS_START',
    FETCH_SHOP_ITEMS_SUCCESS: ' FETCH_SHOP_ITEMS_SUCCESS',
    FETCH_SHOP_ITEMS_FAILURE: ' FETCH_SHOP_ITEMS_FAILURE',
    FETCH_BRANDS: 'FETCH_BRANDS',
    GET_BRANDS: 'GET_BRANDS',
    GET_SELECT_BRANDS: 'GET_SELECT_BRANDS'
}