export const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_START: ' LOGOUT_START',
    LOGOUT_SUCCESS: ' LOGOUT_SUCCESS',
    LOGOUT_FAIL: ' LOGOUT_FAIL',
    USER_LOADING: 'USER_LOADING',
    USER_LOADED: 'USER_LOADED',
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL'
}